apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: config-service
  name: config-service
  namespace: default
spec:
  replicas: 2
  minReadySeconds: 45
  selector:
    matchLabels:
      app: config-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: config-service
    spec:
      containers:
      - image: ${REPOSITORY_TAG} #CHANGE
        imagePullPolicy: IfNotPresent
        name: config-service
        ports:
        - name: liveness-port
          containerPort: 8012
#        env: //CHANGE
#          - name: CURRENCY_EXCHANGE_URI
#            value: http://currency-exchange
        livenessProbe:
          httpGet:
            path: /ConfigServer/default
            port: 8012
          initialDelaySeconds: 80
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ConfigServer/default
            port: 8012
          initialDelaySeconds: 80
          periodSeconds: 10
      restartPolicy: Always
      terminationGracePeriodSeconds: 20
      
---

apiVersion: v1
kind: Service
metadata:
  labels: #PODS
    app: config-service
  name: config-service
  namespace: default
spec:
  ports:
  - nodePort: 30701 
    port: 8012 
    protocol: TCP
    #targetPort: 8100 
  selector:
    app: config-service
  sessionAffinity: None 
  type: NodePort